<?php

function demo_pages_menu() {
  $items['demo_pages/simple'] = array(
    'title' => 'My first custom page',
    'page callback' => 'demo_pages_simple',
    'access arguments' => array('access content'),
  );

  $items['demo_pages/arguments/%/%'] = array(
    'page callback' => 'demo_pages_arguments',
    'page arguments' => array(2, 3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function demo_pages_simple(){
  return array('#markup' => '<p>' . t('demo rules!') . '</p>');
}

function demo_pages_arguments($first, $second) {
  // Make sure you don't trust the URL to be safe! Always check for exploits.
  if (!is_numeric($first) || !is_numeric($second)) {
    // We will just show a standard "access denied" page in this case.
    drupal_access_denied();
    // We actually don't get here.
    return;
  }

  $list[] = t("First number was @number.", array('@number' => $first));
  $list[] = t("Second number was @number.", array('@number' => $second));
  $list[] = t('The total was @number.', array('@number' => $first + $second));

  $render_array['demo_pages_arguments'] = array(
    // The theme function to apply to the #items.
    '#theme' => 'item_list',
    // The list itself.
    '#items' => $list,
    '#title' => t('Argument Information'),
  );
  return $render_array;
}